# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  # Check for updates weekly
    versioning-strategy: "increase"  # Always try to increase the version
    open-pull-requests-limit: 3  # Limit open pull requests to 3
    ignore:
      - dependency-name: "core"  # Ignore updates for the "core" action
      - dependency-name: "setup-node"
        versions: ["<16"]  # Ignore versions below 16 for "setup-node"
    reviewers:
      - users:
          - "carlosferreyra"
      - teams:
          - "security-team"
    labels:
      - "dependabot"
      - "dependencies"