# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "jinja2",
# ]
# ///
"""
Renders README.md from README.md.j2 + data/resumes.json.

All data-driven content (name, skills, experience, projects, certifications,
links) is sourced from the `carlos-ferreyra` combo resume inside resumes.json
(generated by scripts/resume_build.py — git is the source of truth). Static
narrative sections (GitHub stats widgets, "Working on" bullets) live in the
template itself.

Usage:
    uv run scripts/build_readme.py
    uv run scripts/build_readme.py --out README.md
"""

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def build_links(raw: list[dict]) -> dict:
    """Flatten links list into a {id: url} dict for easy template access."""
    return {l["id"]: l["url"] for l in raw}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render README.md from README.md.j2 + resume.json."
    )
    parser.add_argument(
        "--out", default="README.md", help="Output path (relative to repo root)"
    )
    args = parser.parse_args()

    repo_root = Path(__file__).parent.parent
    resumes_path = repo_root / "data" / "resumes.json"
    template_path = repo_root / "README.md.j2"
    out_path = repo_root / args.out
    public_slug = "carlos-ferreyra"

    if not template_path.exists():
        raise SystemExit(f"ERROR: {template_path} not found.")
    if not resumes_path.exists():
        raise SystemExit(f"ERROR: {resumes_path} not found — run scripts/resume_build.py first.")

    resumes = json.loads(resumes_path.read_text())["resumes"]
    resume = next((r for r in resumes if r["slug"] == public_slug), None)
    if resume is None:
        raise SystemExit(f"ERROR: resumes.json missing required slug '{public_slug}'.")

    env = Environment(
        loader=FileSystemLoader(str(repo_root)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["slugify"] = slugify

    # Pre-render skills block with aligned columns
    skills_block = "\n".join(
        f"{(g['category'] + ':'):<24} {', '.join(g['items'])}" for g in resume["skills"]
    )

    template = env.get_template("README.md.j2")
    output = template.render(
        info=resume["personalInfo"],
        github=resume["githubUsername"],
        links=build_links(resume["links"]),
        skills=resume["skills"],
        skills_block=skills_block,
        experience=resume["experience"],
        education=resume["education"],
        certifications=resume["certifications"],
        projects=resume["projects"],
        last_update=datetime.now(timezone.utc).strftime("%Y"),
    )

    out_path.write_text(output)
    print(f"README.md written to {out_path}")


if __name__ == "__main__":
    main()
