# make a cron job for daily tasks

name: Daily Cron

env:
  CNAME_URL: carlosferreyra.me

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC
    

jobs:
  upload-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create PDFs directory
        run: mkdir -p ./pdfs
        
      - name: Download PDF
        run: |
          set -e
          curl -L -o ./pdfs/me.pdf https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/me.pdf
          curl -L -o ./pdfs/me_spanish.pdf https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/me_spanish.pdf

      - name: Set up repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Upload PDFs
        run: |
          git add pdfs/me.pdf pdfs/me_spanish.pdf
          git commit -m "Daily PDF upload [$(date '+%b %dth, %Y')]"
          git push
  
  update-cnames:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub bot permissions
        run: |
          set -e
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://github.com" > ~/.git-credentials

      - name: Fetch list of repositories
        id: repo-list
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos?per_page=100 \
               > repos.json
          cat repos.json

      - name: Update CNAME for all repositories
        run: |
          set -e
          for repo in $(jq -r '.[].clone_url' repos.json); do
            echo "Cloning $repo"
            git clone $repo
            repo_name=$(basename $repo .git)
            echo "Updating CNAME for $repo_name"
            echo "${{ env.CNAME_URL }}" > $repo_name/CNAME
            git -C $repo_name add CNAME
            git -C $repo_name commit -m "Update CNAME to ${{ env.CNAME_URL }}"
            git -C $repo_name push
          rm -rf repos.json