name: Hourly Cron

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_API_URL: https://api.github.com

permissions:
  contents: read
  packages: read
  repository-projects: write

jobs:
  update-repo-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch GitHub repositories from carlosferreyra
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" $GITHUB_API_URL/users/carlosferreyra/repos?per_page=100 > user_repos.json

      - name: Fetch GitHub repositories from organizations (Seminario-Integrador-2024)
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" $GITHUB_API_URL/orgs/Seminario-Integrador-2024/repos?per_page=100 > org_repos.json

      - name: Fetch social preview images from carlosferreyra repositories
        run: |
          echo "{}" > social_previews.json
          jq -r '.[] | select(.name | startswith(".") | not) | .name' user_repos.json org_repos.json | while read repo; do
            owner="carlosferreyra"
            if [[ $repo == *"/"* ]]; then
              owner=$(echo $repo | cut -d'/' -f1)
              repo=$(echo $repo | cut -d'/' -f2)
            fi
            query="{\"query\":\"query { repository(owner: \\\"$owner\\\", name: \\\"$repo\\\") { openGraphImageUrl } }\"}"
            img_url=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" \
                      -H "Content-Type: application/json" \
                      -X POST \
                      -d "$query" \
                      $GITHUB_API_URL/graphql | tee /dev/stderr | jq -r ".data.repository.openGraphImageUrl")
            jq --arg repo "$repo" --arg img_url "$img_url" '.[$repo] = $img_url' social_previews.json > tmp.json && mv tmp.json social_previews.json
          done

      - name: Fetch social preview images from orgs repositories (Seminario-Integrador-2024)
        run: |
          echo "{}" > social_previews_orgs.json
          jq -r '.[] | select(.name | startswith(".") | not) | .name' org_repos.json | while read repo; do
            owner="Seminario-Integrador-2024"
            query="{\"query\":\"query { repository(owner: \\\"$owner\\\", name: \\\"$repo\\\") { openGraphImageUrl }}\"}"
            
            img_url=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" \
                          -H "Content-Type: application/json" \
                          -X POST \
                          -d "$query" \
                          $GITHUB_API_URL/graphql | tee /dev/stderr | jq -r ".data.repository.openGraphImageUrl")
            
            if [ "$img_url" != "null" ] && [ -n "$img_url" ]; then
              jq --arg repo "$repo" --arg img_url "$img_url" '.[$repo] = $img_url' social_previews_orgs.json > tmp.json && mv tmp.json social_previews_orgs.json
            fi
          done
          

      - name: Save repositories and social previews to projects.js
        run: |
          echo "const projects = [" > projects.js
          jq -r --slurpfile previews social_previews.json \
               --slurpfile org_previews social_previews_orgs.json \
               '.[] | select(.name | startswith(".") | not) | select(.homepage != null and .homepage != "") | {
                 "name": .name,
                 "img": (if .owner.type == "Organization" then $org_previews[0][.name] else $previews[0][.name] end),
                 "repo": .html_url,
                 "demo": .homepage,
                 "stack": (.topics // []),
                 "description": (.description // "" | gsub("\""; "\\\""))
               }' org_repos.json user_repos.json | \
          jq -r 'to_entries | .[] | "  {\n    name: \"\(.value.name)\",\n    img: \"\(.value.img)\",\n    repo: \"\(.value.repo)\",\n    demo: \"\(.value.demo)\",\n    stack: [\"\(.value.stack | join("\", \""))\"],\n    description: \"\(.value.description)\"\n  },"' >> projects.js
          
          echo "];
          
          export default projects;" >> projects.js
          
          rm user_repos.json org_repos.json social_previews.json social_previews_orgs.json

      - name: Commit and push changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          else
            git add projects.js
            git commit -m "Update projects.js with latest repositories"
            git push