name: Repository Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update-repo-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch GitHub repositories from user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/carlosferreyra/repos?per_page=100 > user_repos.json

      - name: Fetch GitHub repositories from organization
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/orgs/Seminario-Integrador-2024/repos?per_page=100 > org_repos.json

      - name: Save repositories to projects.js
        run: |
          if [ ! -f user_repos.json ] || [ ! -f org_repos.json ]; then
            echo "Failed to fetch repositories"
            exit 1
          fi
          if [ -f projects.js ]; then
            rm projects.js
          fi
          echo "const projects = [" > projects.js
          jq -r '.[] | select(.name | startswith(".") | not) | {
            "name": .name,
            "img": .owner.avatar_url,
            "repo": .html_url,
            "demo": "\"\(.homepage)\"",
            "stack": (.topics // []),
            "description": (.description // "" | gsub("\""; "\\\""))
          } | "  {\n    name: \"\(.name)\",\n    img: \"\(.img)\",\n    repo: \"\(.repo)\",\n    demo: \(.demo),\n    stack: [\"\(.stack | join("\", \""))\"],\n    description: \"\(.description)\"\n  },"' user_repos.json org_repos.json >> projects.js
          echo "];
          
          export default projects;" >> projects.js
          
          rm user_repos.json org_repos.json

      - name: Commit and push changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          else
            git add projects.js
            git commit -m "Update projects.js with latest repositories"
            git push
          fi
