name: Daily Cron

env:
  CNAME_URL: carlosferreyra.me
  GITHUB_API_URL: https://api.github.com
  PDF_RESUME_URL: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/me.pdf
  PDF_RESUME_ES_URL: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/me_spanish.pdf
  PDF_DIR: ./pdfs
  USER_NAME: 'github-actions[bot]'
  USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
  PER_PAGE: 100

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

jobs:
  upload-pdfs:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.update-pdfs.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create PDFs directory
        run: mkdir -p ${{ env.PDF_DIR }}
        
      - name: Download and Update PDFs
        id: update-pdfs
        run: |
          set -e
          SUCCESS=false
          curl -L -o ${{ env.PDF_DIR }}/me.pdf ${{ env.PDF_RESUME_URL }}
          curl -L -o ${{ env.PDF_DIR }}/me_spanish.pdf ${{ env.PDF_RESUME_ES_URL }}
          
          git config --global user.name '${{ env.USER_NAME }}'
          git config --global user.email '${{ env.USER_EMAIL }}'
          
          if git diff --quiet ${{ env.PDF_DIR }}; then
            echo "No changes in PDFs"
            echo "status=unchanged" >> $GITHUB_OUTPUT
          else
            git add ${{ env.PDF_DIR }}/*.pdf
            git commit -m "📄 PDF Update [$(date '+%Y-%m-%d %H:%M:%S UTC')] - Successfully updated resume files"
            git push
            echo "status=updated" >> $GITHUB_OUTPUT
          fi

  update-cnames:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.update-cnames.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub bot permissions
        run: |
          git config --global user.name '${{ env.USER_NAME }}'
          git config --global user.email '${{ env.USER_EMAIL }}'
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://github.com" > ~/.git-credentials

      - name: Update CNAME files
        id: update-cnames
        run: |
          set -e
          UPDATED_COUNT=0
          
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "${{ env.GITHUB_API_URL }}/user/repos?per_page=${{ env.PER_PAGE }}" > repos.json

          for repo in $(jq -r '.[].clone_url' repos.json); do
            echo "Processing $repo"
            git clone $repo
            repo_name=$(basename $repo .git)
            
            if [ ! -f "$repo_name/CNAME" ] || [ "$(cat $repo_name/CNAME)" != "${{ env.CNAME_URL }}" ]; then
              echo "${{ env.CNAME_URL }}" > $repo_name/CNAME
              git -C $repo_name add CNAME
              git -C $repo_name commit -m "🌐 CNAME Update [$(date '+%Y-%m-%d %H:%M:%S UTC')] - Set to ${{ env.CNAME_URL }}"
              git -C $repo_name push
              ((UPDATED_COUNT++))
            fi
          done
          
          rm -rf repos.json
          echo "status=updated_$UPDATED_COUNT" >> $GITHUB_OUTPUT