name: Hourly Repository Update

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours

env:
  GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm run app
      - run: npm run update-pages
      - run: |
          git config user.name carlosferreyra
          git config user.email eduferreyraok@gmail.com
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update repo with latest info"
          git push origin main
