on:
  workflow_run:
      workflows: ["Update PDFs"]
      types:
          - completed
      branches:
          - main

jobs:
  upload-pdf:
    name: Upload PDFs to Google Drive
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload PDF to Google Drive
        env:
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
        run: |
          for file in ./pdfs/*.pdf; do
            curl -X POST -L \
              -H "Authorization: Bearer $GOOGLE_DRIVE_API_KEY" \
              -F "metadata={name : \"$(basename $file)\"};type=application/json;charset=UTF-8" \
              -F "file=@$file;type=application/pdf" \
              "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
          done