name: Update PDFs

env:
  PDF_URL_EN: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/carlos-ferreyra.pdf
  PDF_URL_ES: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/carlos-ferreyra-espanol.pdf
  USER_NAME: "github-actions[bot]"
  USER_EMAIL: "github-actions[bot]@users.noreply.github.com"

  permissions:
  contents: write

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 */1 * * *" # Runs every hour
jobs:
  upload-pdfs:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.update-pdfs.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Update Resumes
        id: update-pdfs
        run: npm run update-resumes
