name: Update PDFs

env:
  PDF_RESUME_URL: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/carlos-ferreyra.pdf
  PDF_RESUME_ES_URL: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/carlos-ferreyra-espanol.pdf
  PDF_RESUME_ATS: https://typst.app/project/rT3d3iUFna4DBPxWN3Wm7u
  PDF_DIR: ./pdfs
  PDF_EN_FILENAME: carlos-ferreyra-EN.pdf
  PDF_ES_FILENAME: carlos-ferreyra-ES.pdf
  PDF_ATS_FILENAME: carlos-ferreyra.pdf
  USER_NAME: 'github-actions[bot]'
  USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
jobs:
  upload-pdfs:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.update-pdfs.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }} # Use a PAT token for authentication

      - name: Create PDFs directory
        run: |
            if [ ! -d "${{ env.PDF_DIR }}" ]; then
            mkdir -p ${{ env.PDF_DIR }}
            fi
        
      - name: Download and Update PDFs
        id: update-pdfs
        run: |
          set -e
          
          # Add authentication headers and error handling
          URLS=("${{ env.PDF_RESUME_URL }}" "${{ env.PDF_RESUME_ES_URL }}" "${{ env.PDF_RESUME_ATS }}")
          FILENAMES=("${{ env.PDF_EN_FILENAME }}" "${{ env.PDF_ES_FILENAME }}" "${{ env.PDF_ATS_FILENAME }}")
          CHANGED=false
          
          for i in "${!URLS[@]}"; do
            URL="${URLS[$i]}"
            FILENAME="${FILENAMES[$i]}"
            HTTP_CODE=$(curl -L -w "%{http_code}" -o "${{ env.PDF_DIR }}/$FILENAME" "$URL")
            if [ "$HTTP_CODE" != "200" ]; then
              echo "Failed to download PDF from $URL (HTTP $HTTP_CODE)"
              exit 1
            fi
            
            if ! cmp -s "${{ env.PDF_DIR }}/$FILENAME" "$FILENAME"; then
              CHANGED=true
            fi
          done
          
          if [ "$CHANGED" = true ]; then
            git config --global user.name '${{ env.USER_NAME }}'
            git config --global user.email '${{ env.USER_EMAIL }}'
            
            git add ${{ env.PDF_DIR }}/*.pdf
            git commit -m "📄 PDF Update [$(date '+%Y-%m-%d %H:%M:%S UTC')] - Successfully updated resume files"
            git push
            echo "status=updated" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in PDF files."
            echo "status=unchanged" >> $GITHUB_OUTPUT
          fi