name: Update Resume PDFs

env:
  PDF_RESUME_URL: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/carlos-ferreyra.pdf
  PDF_RESUME_ES_URL: https://storage.rxresu.me/clz62ydvs5a9cvrn3hvbh93tp/resumes/carlos-ferreyra-espanol.pdf
  PDF_DIR: ./pdfs
  PDF_EN_FILENAME: carlos-ferreyra-EN.pdf
  PDF_ES_FILENAME: carlos-ferreyra-ES.pdf
  PDF_ATS_FILENAME: carlos-ferreyra.pdf
  USER_NAME: "github-actions[bot]"
  USER_EMAIL: "github-actions[bot]@users.noreply.github.com"

on:
  workflow_call: # Allows calling this workflow from another workflow
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC
jobs:
  upload-pdfs:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.update-pdfs.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # Use a PAT token for authentication

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Update Resumes
        id: update-pdfs
        run: npm run update-resumes
        env:
          PDF_RESUME_URL: ${{ env.PDF_RESUME_URL }}
          PDF_RESUME_ES_URL: ${{ env.PDF_RESUME_ES_URL }}
          PDF_DIR: ${{ env.PDF_DIR }}
          PDF_EN_FILENAME: ${{ env.PDF_EN_FILENAME }}
          PDF_ES_FILENAME: ${{ env.PDF_ES_FILENAME }}
          USER_NAME: ${{ env.USER_NAME }}
          USER_EMAIL: ${{ env.USER_EMAIL }}
